# Generated by Django 4.1.1 on 2022-09-11 14:50

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='userName',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name=django.contrib.auth.models.User),
        ),
    ]
