# Generated by Django 4.1.1 on 2022-09-11 14:52

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_product_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='userName',
            field=models.CharField(default=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL), max_length=200, verbose_name=django.contrib.auth.models.User),
        ),
    ]
