# Generated by Django 4.1.1 on 2022-09-11 14:55

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_product_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='userName',
            field=models.CharField(default=django.contrib.auth.models.User, max_length=200),
        ),
    ]
