# Generated by Django 4.1.1 on 2022-09-11 14:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_product_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='userName',
            field=models.CharField(default=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL), max_length=200),
        ),
    ]
