# Generated by Django 4.1.1 on 2022-09-11 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_product_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='userName',
        ),
    ]
