# Generated by Django 4.1.1 on 2022-09-11 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_product_condition'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='countInStock',
        ),
        migrations.AddField(
            model_name='product',
            name='phoneNumber',
            field=models.CharField(default='000000000', max_length=12),
        ),
    ]
