# Generated by Django 4.1.1 on 2023-02-22 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_product_slug_category_alter_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
    ]
